### PR TITLE
Allow disable of the auto-anonymous login feature

### PR DESCRIPTION
**Pull request by kevin-btc**

### CODE REVIEW

**Comment by lowczarc** [comment]
I don't think we should remove the feature if this causes issues, let's find a way resolve the issue instead.
I'm rename the PR and convert it to draft.
For the record. The problem is when trying to add an email to the anonymous connexion, the auto connection breaks it.

**Comment by victorforissier** [comment]
Oui tu as raison de réfléchir comme ça !

Sent via Superhuman ( ***@***.*** )

**Comment by kevin-btc** [comment]
To rectify, I didn't remove it because it was causing a problem, I removed it because this code seemed useless and was causing a problem, so it's not really very useful, it's just a 'nice to have' for devs.

**Comment by victorforissier** [comment]
C'était pas inutile, c'était pour permettre aux devs de setup et de tester Polyfire plus vite pour réduire le churn qui est notre problème principale aujourd'hui.

Sent via Superhuman ( ***@***.*** )

**Review by lowczarc — APPROVED** [review]
LGTM

**Pull request merged**
